services:
  browser:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: pravda
      POSTGRES_PASSWORD: pravda
      POSTGRES_DB: pravda
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata:
